name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Snowflake Connector
        run: |
          pip install snowflake-connector-python
      
      - name: Execute SQL in Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          python - <<EOF
          import snowflake.connector
          import os
          
          conn = snowflake.connector.connect(
              account=os.environ['SNOWFLAKE_ACCOUNT'],
              user=os.environ['SNOWFLAKE_USER'],
              password=os.environ['SNOWFLAKE_PASSWORD'],
              warehouse=os.environ['SNOWFLAKE_WAREHOUSE'],
              role=os.environ['SNOWFLAKE_ROLE']
          )
          
          with open('sql/create_table.sql', 'r') as f:
              sql_script = f.read()
          
          cursor = conn.cursor()
          for statement in sql_script.split(';'):
              if statement.strip():
                  cursor.execute(statement)
          
          cursor.close()
          conn.close()
          print("✅ SQL executed successfully!")
          EOF
